#!/bin/bash

Msize=$(grep -A 1 ${raw_dir}${run}'/method' -e '##$PVM_Matrix=( 2 )')
Msize=(${Msize#*)})
echo ${Msize[0]} 
echo ${Msize[1]} 

Fov=$(grep -A 1 ${raw_dir}${run}'/method' -e '##$PVM_Fov=( 2 )')
Fov=(${Fov#*)})
Fov1=$(bc <<<"scale=2;${Fov[0]}/2")
Fov2=$(bc <<<"scale=2;${Fov[1]}/2")
echo ${Fov2} 

Nslice=$(grep -A 1 ${raw_dir}${run}'/method' -e '##$PVM_SPackArrNSlices=( 1 )')
Nslice=(${Nslice#*)})
echo ${Nslice}
Tslice=$(grep ${raw_dir}${run}'/method' -e '##$PVM_SliceThick=')
Tslice=(${Tslice#*=})
echo ${Tslice}

Fov3=$(bc <<<"scale=2;${Tslice}*${Nslice}/2")
echo ${Fov3}


Rez=$(grep -A 1 ${raw_dir}${run}'/method' -e '##$PVM_SpatResol=( 2 )')
Rez=(${Rez#*)})
echo ${Rez[0]}

if [ 1 -eq "$(echo "${Rez[0]} < ${Rez[1]}" | bc)" ]
then
MinRez=${Rez[0]}
else
MinRez=${Rez[1]}
fi

if [ 1 -eq "$(echo "${Tslice} < ${MinRez}" | bc)" ]
then
MinRez=${Tslice}
fi

echo ${MinRez}
