#!/bin/bash
# every time change something, please save it!



type=an200epi
filename=${date}.${mouse_num}.restforave_${duration}
rm ${pro_dir}proc.${filename}
rm ${pro_dir}output.proc.${filename}
rm -rf ${pro_dir}${filename}.results

formean=()
for run in "${EPI_num[@]}"
do 
formean[${#formean[*]}]=reg10.${filen}${run}.${type}_regtotemp+orig.HEAD
3dcalc -a reg.${filen}${run}.${type}_regtotemp+orig -expr 'a+100' -prefix reg10.${filen}${run}.${type}_regtotemp
done


afni_proc.py -subj_id ${filename}              \
-dsets ${formean[*]}  \
-copy_anat ${template_dir}${anat}         \
-anat_has_skull no                              \
-blocks despike volreg mask blur scale regress        \
-volreg_post_vr_allin yes                       \
-volreg_pvra_base_index MIN_OUTLIER             \
-mask_epi_anat no                               \
-mask_import 100mask ${template_dir}${mask}	\
-mask_apply 100mask				\
-blur_size 0.1                                  \
-regress_censor_motion 0.5                      \
-regress_censor_outliers 0.02                  \
-regress_apply_mot_types demean deriv           \
-regress_motion_per_run                         \
-regress_run_clustsim no                        

tcsh -xef proc.${filename} |& tee output.proc.${filename}
rm reg10.*
rm ${filename}.results/pb0*
rm ${filename}.results/fitts*
